name: CodeSentinel AI Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  codesentinel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Run CodeSentinel AI
        uses: kushmunjal/codesentinel-ai@main
        with:
          provider: 'openai'
          model: 'gpt-4o'
          api_key: ${{ secrets.LLM_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
